version: '3.9'

services:
  movie-api:
    image: trybe/movie-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOSTNAME=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=movies-api
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
        - ../movies-api.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root